sudo: false
os:
  - linux
  - osx
language: node_js
node_js:
  - '8'
  - '10'
before_install:
  - npm install npminstall -g
install:
  - npminstall
  - npminstall codecov
script:
  - npm run ci
after_script:
  - codecov
